version: "3.9"

services:
  mpd:
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
    volumes:
      - ./config/docker.pulse.mpd.conf:/root/.config/mpd/mpd.conf:rw

  spotify:
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713

  jukebox:
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
